/**
 * Generate Kedro catalog.yml from datasets
 */

import type { KedroDataset } from '../../types/kedro';
import { DATASET_TYPE_MAPPING } from '../../constants/datasetTypes';
import { inferDataLayer, getFileExtension, escapeYamlString, toSnakeCase } from './helpers';

// Dataset types that use no filepath at all
const NO_FILEPATH_TYPES = new Set([
  'MemoryDataset',
  'pandas.SQLTableDataset', // uses credentials + load_args.table_name instead
]);

// SQLQueryDataset uses inline sql + credentials (filepath to a .sql file is supported but uncommon)
const SQL_QUERY_TYPE = 'pandas.SQLQueryDataset';

/**
 * Generate Kedro catalog.yml file content from dataset definitions.
 * Creates a YAML data catalog with type, filepath, layer, and versioning config.
 *
 * @param datasets - Array of dataset definitions
 * @returns Complete catalog.yml file content as string
 */
export function generateCatalog(datasets: KedroDataset[]): string {
  const header = `# Data Catalog
# Generated by Kedro Pipeline Builder
#
# Here you can define all your data sources, such as CSV files, databases,
# and custom data loaders. Kedro supports a variety of data formats and
# storage systems.
#
# Documentation: https://docs.kedro.org/en/stable/data/data_catalog.html

`;

  if (datasets.length === 0) {
    return header + '# No datasets defined\n';
  }

  const entries = datasets.map((ds) => generateCatalogEntry(ds));

  return header + entries.join('\n\n') + '\n';
}

/**
 * Generate a single catalog entry in YAML format.
 * Includes type, filepath, layer, and versioning configuration.
 */
function generateCatalogEntry(dataset: KedroDataset): string {
  const datasetName = dataset.name;

  // Determine Kedro dataset type
  const kedroType = dataset.type
    ? DATASET_TYPE_MAPPING[dataset.type.toLowerCase()] || dataset.type
    : 'pandas.CSVDataset';

  // Check if filepath was provided by user
  const userFilepath = dataset.filepath?.trim();

  // Generate filepath if not provided (auto infer sensible default)
  const filepath = userFilepath && userFilepath.length > 0
    ? userFilepath
    : inferFilepath(datasetName, kedroType);
  const hasUserFilepath = Boolean(userFilepath && userFilepath.length > 0);

  let entry = `${datasetName}:
  type: ${kedroType}`;

  if (kedroType === SQL_QUERY_TYPE) {
    // SQLQueryDataset uses inline sql + credentials — the recommended pattern per Kedro docs
    entry += `\n  sql: "SELECT * FROM your_table"  # Replace with your SQL query`;
    entry += `\n  credentials: db_credentials  # Configure in conf/local/credentials.yml`;
  } else if (!NO_FILEPATH_TYPES.has(kedroType)) {
    // Standard file-based dataset — add data filepath
    entry += `\n  filepath: ${escapeYamlString(filepath)}`;
    if (!hasUserFilepath) {
      entry += '  # Auto-generated – update with your actual data location';
    }
  } else if (kedroType === 'pandas.SQLTableDataset') {
    // SQLTableDataset has no filepath — table_name is a top-level constructor argument
    entry += `\n  credentials: db_credentials  # Configure in conf/local/credentials.yml`;
    entry += `\n  table_name: your_table_name  # Replace with actual table name`;
  }

  // Add layer if specified
  if (dataset.layer) {
    entry += `\n  layer: ${dataset.layer}`;
  }

  // Add versioning if enabled (time-travel and audit trails)
  if (dataset.versioned && !NO_FILEPATH_TYPES.has(kedroType)) {
    entry += `\n  versioned: true`;
  }

  return entry;
}

/**
 * Infer filepath from dataset name and type.
 * Generates a sensible default path in data/{layer}/{name}{ext} format.
 */
function inferFilepath(name: string, kedroType: string): string {
  const safeName = toSnakeCase(name) || 'dataset';
  const layer = inferDataLayer(safeName);
  const extension = getFileExtension(kedroType);

  return `data/${layer}/${safeName}${extension}`;
}
