/**
 * Generate Kedro nodes.py from pipeline nodes
 */

import type { KedroNode, KedroDataset, KedroConnection } from '../../types/kedro';
import {
  toSnakeCase,
  formatFunctionParams,
  indentCode,
  getNodeInputDatasets,
  getNodeOutputDatasets,
} from './helpers';

/**
 * Generate Kedro nodes.py file content from pipeline nodes.
 * Creates Python functions for each node with proper signatures and optional custom code.
 *
 * @param nodes - Pipeline nodes to generate functions for
 * @param connections - Connections to determine inputs/outputs
 * @param datasets - Dataset definitions by ID
 * @param pipelineName - Name of the pipeline
 * @returns Complete nodes.py file content as string
 */
export function generateNodes(
  nodes: KedroNode[],
  connections: KedroConnection[],
  datasets: Record<string, KedroDataset>,
  pipelineName: string
): string {
  const header = `"""
Node functions for ${pipelineName} pipeline.
Generated by Kedro Pipeline Builder.

This module contains the data processing and transformation functions (nodes)
that make up your Kedro pipeline. Each function should be a pure function that
takes inputs and returns outputs without side effects.
"""

from typing import Dict, Any, Tuple
import pandas as pd
import logging

logger = logging.getLogger(__name__)

`;

  if (nodes.length === 0) {
    return header + '# No nodes defined\n';
  }

  const functions = nodes.map((node) =>
    generateNodeFunction(node, connections, datasets)
  );

  return header + functions.join('\n\n\n');
}

/**
 * Generate a single node function.
 * Uses custom code if provided, otherwise generates a template function.
 */
function generateNodeFunction(
  node: KedroNode,
  connections: KedroConnection[],
  datasets: Record<string, KedroDataset>
): string {
  const funcName = toSnakeCase(node.name);
  const inputs = getNodeInputDatasets(node, connections, datasets);
  const outputs = getNodeOutputDatasets(node, connections, datasets);

  // Use user's custom code if provided
  if (node.functionCode && node.functionCode.trim()) {
    return generateCustomFunction(funcName, inputs, outputs, node);
  }

  // Generate template function
  return generateTemplateFunction(funcName, inputs, outputs);
}

/**
 * Extract function name from user's Python code.
 * Matches the function definition pattern and returns the name.
 */
function extractFunctionName(code: string): string | null {
  const match = code.match(/def\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(/);
  return match ? match[1] : null;
}

/**
 * Generate function using user's custom code.
 * Validates function name and wraps code in proper signature if needed.
 */
function generateCustomFunction(
  funcName: string,
  inputs: string[],
  outputs: string[],
  node: KedroNode
): string {
  const userCode = node.functionCode!.trim();

  // Validate that function name in code matches node name
  const extractedFuncName = extractFunctionName(userCode);
  if (extractedFuncName && extractedFuncName !== funcName) {
    // Add a comment warning about the mismatch
    const warning = `# WARNING: Function name "${extractedFuncName}" in your code does not match node name "${funcName}".\n# The pipeline expects the function to be named "${funcName}". Please update your code.\n\n`;

    // Return the user's code as-is but with a warning
    return warning + userCode;
  }

  // If user provided complete function definition, use it as-is
  if (userCode.includes('def ')) {
    return userCode;
  }

  // Otherwise, wrap user's code in a function with proper signature (no docstring)
  const params = formatFunctionParams(inputs);
  const returnType = getReturnType(outputs);
  const indentedCode = indentCode(userCode, 4);

  return `def ${funcName}(${params}) -> ${returnType}:
${indentedCode}`;
}

/**
 * Generate template function with simple placeholder.
 * Creates a function signature with pass statement for user to implement.
 */
function generateTemplateFunction(
  funcName: string,
  inputs: string[],
  outputs: string[]
): string {
  const params = formatFunctionParams(inputs);
  const returnType = getReturnType(outputs);

  // Simple placeholder - just function signature with pass
  return `def ${funcName}(${params}) -> ${returnType}:
    # Implement your custom logic here
    pass`;
}

/**
 * Get return type hint based on number of outputs.
 * Returns None, pd.DataFrame, or Tuple[pd.DataFrame, ...].
 */
function getReturnType(outputs: string[]): string {
  if (outputs.length === 0) return 'None';
  if (outputs.length === 1) return 'pd.DataFrame';
  return `Tuple[${outputs.map(() => 'pd.DataFrame').join(', ')}]`;
}

