/**
 * Generate Kedro pipeline.py from pipeline structure
 */

import type { KedroNode, KedroDataset, KedroConnection } from '../../types/kedro';
import { toSnakeCase, formatNodeInputs, formatNodeOutputs, getNodeInputDatasets, getNodeOutputDatasets } from './helpers';

/**
 * Generate Kedro pipeline.py file content from pipeline structure.
 * Creates a complete Python module with imports and node definitions.
 *
 * @param nodes - Pipeline nodes to include
 * @param connections - Connections between nodes and datasets
 * @param datasets - Dataset definitions by ID
 * @param pipelineName - Name of the pipeline
 * @returns Complete pipeline.py file content as string
 */
export function generatePipeline(
  nodes: KedroNode[],
  connections: KedroConnection[],
  datasets: Record<string, KedroDataset>,
  pipelineName: string
): string {
  // Separate function nodes from LLM context nodes
  const functionNodes = nodes.filter((n) => n.nodeKind !== 'llm_context');
  const llmContextNodes = nodes.filter((n) => n.nodeKind === 'llm_context');

  // Generate function imports for regular nodes only
  const funcNames = functionNodes.map((n) => toSnakeCase(n.name));
  const funcImports = funcNames.length > 0 ? `from .nodes import ${funcNames.join(', ')}` : '';

  // Determine pipeline imports (node before Pipeline to match Kedro convention)
  const pipelineImports: string[] = ['node'];
  if (llmContextNodes.length > 0) pipelineImports.push('llm_context_node');
  pipelineImports.push('Pipeline');

  // Generate all node definitions (both types)
  const allDefinitions: string[] = [];

  // LLM context nodes first (they produce context objects consumed by function nodes)
  llmContextNodes.forEach((node) => {
    allDefinitions.push(generateLLMContextNodeDefinition(node, connections, datasets));
  });

  // Then function nodes
  functionNodes.forEach((node) => {
    allDefinitions.push(generateNodeDefinition(node, connections, datasets));
  });

  const nodesStr =
    allDefinitions.length > 0
      ? allDefinitions.map((n) => `            ${n},`).join('\n')
      : '';

  return `"""
Pipeline definition for ${pipelineName} pipeline.
Generated by Kedro Pipeline Builder.

This module defines the structure of your pipeline by connecting nodes
with their input and output datasets.
"""

from kedro.pipeline import ${pipelineImports.join(', ')}${funcImports ? '\n' + funcImports : ''}


def create_pipeline(**kwargs) -> Pipeline:
    """
    Create the ${pipelineName} pipeline.

    Returns:
        A Kedro Pipeline object containing all nodes.
    """
    return Pipeline(
        [
${nodesStr}
        ]
    )
`;
}

/**
 * Generate a single node definition for the pipeline.
 * Creates the Kedro node() call with func, inputs, outputs, and name.
 */
function generateNodeDefinition(
  node: KedroNode,
  connections: KedroConnection[],
  datasets: Record<string, KedroDataset>
): string {
  const funcName = toSnakeCase(node.name);
  const inputs = getNodeInputDatasets(node, connections, datasets);
  const outputs = getNodeOutputDatasets(node, connections, datasets);

  const inputsStr = formatNodeInputs(inputs);
  const outputsStr = formatNodeOutputs(outputs);

  return `node(
                func=${funcName},
                inputs=${inputsStr},
                outputs=${outputsStr},
                name="${funcName}_node",
            )`;
}

/**
 * Generate an llm_context_node() call for the pipeline.
 * LLM context nodes use a different API: name, outputs, llm, prompts (no func/inputs).
 * The outputs value is the connected output dataset's name (falls back to node name).
 */
function generateLLMContextNodeDefinition(
  node: KedroNode,
  connections: KedroConnection[],
  datasets: Record<string, KedroDataset>
): string {
  const contextName = toSnakeCase(node.name);

  // Use connected output dataset name so pipeline wiring is correct
  const outputDatasets = getNodeOutputDatasets(node, connections, datasets);
  const outputName = outputDatasets.length > 0 ? outputDatasets[0] : contextName;

  const promptsList = (node.promptNames ?? [])
    .filter((p) => p.trim().length > 0)
    .map((p) => `"${p}"`)
    .join(', ');

  return `llm_context_node(
                name="${contextName}",
                outputs="${outputName}",
                llm="llm",
                prompts=[${promptsList}],
            )`;
}

