/**
 * Generate Kedro pipeline.py from pipeline structure
 */

import type { KedroNode, KedroDataset, KedroConnection } from '../../types/kedro';
import { toSnakeCase, formatNodeInputs, formatNodeOutputs } from './helpers';

/**
 * Generate Kedro pipeline.py file content from pipeline structure.
 * Creates a complete Python module with imports and node definitions.
 *
 * @param nodes - Pipeline nodes to include
 * @param connections - Connections between nodes and datasets
 * @param datasets - Dataset definitions by ID
 * @param pipelineName - Name of the pipeline
 * @returns Complete pipeline.py file content as string
 */
export function generatePipeline(
  nodes: KedroNode[],
  connections: KedroConnection[],
  datasets: Record<string, KedroDataset>,
  pipelineName: string
): string {
  // Generate function imports
  const funcNames = nodes.map((n) => toSnakeCase(n.name));
  const imports = funcNames.length > 0 ? funcNames.join(', ') : '';

  // Generate node definitions
  const nodeDefinitions = nodes.map((node) =>
    generateNodeDefinition(node, connections, datasets)
  );

  const nodesStr =
    nodeDefinitions.length > 0
      ? nodeDefinitions.map((n) => `            ${n},`).join('\n')
      : '';

  return `"""
Pipeline definition for ${pipelineName} pipeline.
Generated by Kedro Pipeline Builder.

This module defines the structure of your pipeline by connecting nodes
with their input and output datasets.
"""

from kedro.pipeline import node, Pipeline${imports ? '\n' : ''}${imports ? `from .nodes import ${imports}` : ''}


def create_pipeline(**kwargs) -> Pipeline:
    """
    Create the ${pipelineName} pipeline.

    Returns:
        A Kedro Pipeline object containing all nodes.
    """
    return Pipeline(
        [
${nodesStr}
        ]
    )
`;
}

/**
 * Generate a single node definition for the pipeline.
 * Creates the Kedro node() call with func, inputs, outputs, and name.
 */
function generateNodeDefinition(
  node: KedroNode,
  connections: KedroConnection[],
  datasets: Record<string, KedroDataset>
): string {
  const funcName = toSnakeCase(node.name);
  const inputs = getNodeInputDatasets(node, connections, datasets);
  const outputs = getNodeOutputDatasets(node, connections, datasets);

  const inputsStr = formatNodeInputs(inputs);
  const outputsStr = formatNodeOutputs(outputs);

  return `node(
                func=${funcName},
                inputs=${inputsStr},
                outputs=${outputsStr},
                name="${funcName}_node",
            )`;
}

/**
 * Get input dataset names for a node.
 * Finds all dataset -> node connections and extracts dataset names.
 */
function getNodeInputDatasets(
  node: KedroNode,
  connections: KedroConnection[],
  datasets: Record<string, KedroDataset>
): string[] {
  const inputs: string[] = [];

  connections.forEach((conn) => {
    // Find connections where dataset -> node
    if (conn.target === node.id && conn.source.startsWith('dataset-')) {
      const dataset = datasets[conn.source];
      if (dataset) {
        inputs.push(dataset.name);
      }
    }
  });

  return inputs;
}

/**
 * Get output dataset names for a node.
 * Finds all node -> dataset connections and extracts dataset names.
 */
function getNodeOutputDatasets(
  node: KedroNode,
  connections: KedroConnection[],
  datasets: Record<string, KedroDataset>
): string[] {
  const outputs: string[] = [];

  connections.forEach((conn) => {
    // Find connections where node -> dataset
    if (conn.source === node.id && conn.target.startsWith('dataset-')) {
      const dataset = datasets[conn.target];
      if (dataset) {
        outputs.push(dataset.name);
      }
    }
  });

  return outputs;
}
